### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by v-yuyao** [v-yuyao/Stu-SB-Chatbot#1]
- [ ] Update project profile

- [ ] Add maven to manage dependency

- [ ] Update README.md
